version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tutorias_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tutorias123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Aplicación principal (Backend + Frontend)
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:tutorias123@postgres:5432/tutorias_db
      - SECRET_KEY=tutorias-docker-secret-key-2025
      - ALLOWED_ORIGINS=http://localhost:8000,http://localhost:5173
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend

volumes:
  postgres_data:
